version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    ports:
    - "${EXPOSE_PORT}:${VITE_PORT}"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    command: npm run dev